### ISSUE TITLE
ImportError: No module named core_rnn_cell_impl

### ISSUE THREAD

**Issue by IdoWSC** [akosiorek/hart#5]
Hi,
I'm using tensorflow 1.2.1 an i get the following error:

`ImportErrorTraceback (most recent call last)
<ipython-input-2-4af6a803ea3e> in <module>()
      9 from hart.data.kitti.tools import get_data
     10 from hart.model import util
---> 11 from hart.model.attention_ops import FixedStdAttention
     12 from hart.model.eval_tools import log_norm, log_ratios, log_values, make_expr_logger
     13 from hart.model.tracker import HierarchicalAttentiveRecurrentTracker as HART

/home/wscuser/notebooks/hart/hart/model/attention_ops.py in <module>()
     22 import numpy as np
     23 import tensorflow as tf
---> 24 from tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl import LSTMCell
     25 from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
     26 from tensorflow.python.util import nest

ImportError: No module named core_rnn_cell_impl`

**Comment by akosiorek** [comment]
This was written using Tensorflow 1.1. Later versions of TF have renamed
and moved some of the modules, hence breaking backward compatibility.

You just need to change the import in 'attention_ops.py' to import an
appropriate LSTM cell.

On 23 Jan 2018 2:36 pm, "IdoWSC" <notifications@github.com> wrote:

Hi,
I'm Using tensorflow 1.2.1 an i get the following error:

ImportErrorTraceback (most recent call last)
in ()
9 from hart.data.kitti.tools import get_data
10 from hart.model import util
---> 11 from hart.model.attention_ops import FixedStdAttention
12 from hart.model.eval_tools import log_norm, log_ratios, log_values,
make_expr_logger
13 from hart.model.tracker import HierarchicalAttentiveRecurrentTracker as
HART

/home/wscuser/notebooks/hart/hart/model/attention_ops.py in ()
22 import numpy as np
23 import tensorflow as tf
---> 24 from tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl import
LSTMCell
25 from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
26 from tensorflow.python.util import nest

ImportError: No module named core_rnn_cell_impl

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akosiorek/hart/issues/5>, or mute the thread

**Comment by IdoWSC** [comment]
for tensorflow v1.2:
In /hart/model/attention_ops.py line 24-25:

-from tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl import LSTMCell
-from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
+from tensorflow.contrib.rnn import LSTMCell
+from tensorflow.contrib.rnn import RNNCell

In /hart/model/rnn.py line 26:

-from tensorflow.python.ops.rnn_cell_impl import _RNNCell as RNNCell
+from tensorflow.contrib.rnn import RNNCell

**Comment by akosiorek** [comment]
thanks for fixing this!
